// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package kpfsiface provides an interface to enable mocking the kpfs service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package kpfsiface

import (
	"github.com/KscSDK/ksc-sdk-go/service/kpfs"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

type KpfsAPI interface {

	DescribePerformanceOnePosixAclList(*map[string]interface{}) (*map[string]interface{}, error)
	DescribePerformanceOnePosixAclListWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribePerformanceOnePosixAclListRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdatePerformanceOnePosixAcl(*map[string]interface{}) (*map[string]interface{}, error)
	UpdatePerformanceOnePosixAclWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdatePerformanceOnePosixAclRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})


	DeletePerformanceOnePosixAcl(*map[string]interface{}) (*map[string]interface{}, error)
	DeletePerformanceOnePosixAclWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeletePerformanceOnePosixAclRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

}

var _ KpfsAPI = (*kpfs.Kpfs)(nil)
