// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package postgresqliface provides an interface to enable mocking the postgresql service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package postgresqliface

import (
	"github.com/KscSDK/ksc-sdk-go/service/postgresql"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

// PostgresqlAPI provides an interface to enable mocking the
// postgresql.Postgresql service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // postgresql.
//    func myFunc(svc postgresqliface.PostgresqlAPI) bool {
//        // Make svc.AllocateDBInstanceEip request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := postgresql.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockPostgresqlClient struct {
//        postgresqliface.PostgresqlAPI
//    }
//    func (m *mockPostgresqlClient) AllocateDBInstanceEip(input *map[string]interface{}) (*map[string]interface{}, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockPostgresqlClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type PostgresqlAPI interface {
	AllocateDBInstanceEip(*map[string]interface{}) (*map[string]interface{}, error)
	AllocateDBInstanceEipWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AllocateDBInstanceEipRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CloneSecurityGroup(*map[string]interface{}) (*map[string]interface{}, error)
	CloneSecurityGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CloneSecurityGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateDBBackup(*map[string]interface{}) (*map[string]interface{}, error)
	CreateDBBackupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateDBBackupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateDBInstance(*map[string]interface{}) (*map[string]interface{}, error)
	CreateDBInstanceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateDBInstanceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateDBInstanceReadReplica(*map[string]interface{}) (*map[string]interface{}, error)
	CreateDBInstanceReadReplicaWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateDBInstanceReadReplicaRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateDBParameterGroup(*map[string]interface{}) (*map[string]interface{}, error)
	CreateDBParameterGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateDBParameterGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateInstanceAccount(*map[string]interface{}) (*map[string]interface{}, error)
	CreateInstanceAccountWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateInstanceAccountRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateInstanceDatabase(*map[string]interface{}) (*map[string]interface{}, error)
	CreateInstanceDatabaseWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateInstanceDatabaseRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateSecurityGroup(*map[string]interface{}) (*map[string]interface{}, error)
	CreateSecurityGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateSecurityGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteDBBackup(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteDBBackupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteDBBackupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteDBInstance(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteDBInstanceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteDBInstanceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteDBParameterGroup(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteDBParameterGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteDBParameterGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteInstanceAccount(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteInstanceAccountWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteInstanceAccountRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteInstanceDatabase(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteInstanceDatabaseWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteInstanceDatabaseRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteSecurityGroup(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteSecurityGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteSecurityGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeCollations(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeCollationsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeCollationsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBBackups(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBBackupsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBBackupsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBEngineVersions(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBEngineVersionsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBEngineVersionsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBInstanceExtensions(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBInstanceExtensionsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBInstanceExtensionsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBInstanceParameters(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBInstanceParametersWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBInstanceParametersRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBInstances(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBInstancesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBInstancesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBLogFiles(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBLogFilesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBLogFilesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeDBParameterGroup(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeDBParameterGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeDBParameterGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeEngineDefaultParameters(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeEngineDefaultParametersWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeEngineDefaultParametersRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeInstanceAccounts(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeInstanceAccountsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeInstanceAccountsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeInstanceDatabases(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeInstanceDatabasesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeInstanceDatabasesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeSecurityGroup(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeSecurityGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeSecurityGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBBackupPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBBackupPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBBackupPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBInstance(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBInstanceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBInstanceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBInstanceAvailabilityZone(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBInstanceAvailabilityZoneWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBInstanceAvailabilityZoneRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBInstanceExtension(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBInstanceExtensionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBInstanceExtensionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBInstanceSpec(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBInstanceSpecWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBInstanceSpecRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBNetwork(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBNetworkWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBNetworkRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyDBParameterGroup(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyDBParameterGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyDBParameterGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyInstanceAccountInfo(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyInstanceAccountInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyInstanceAccountInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyInstanceDatabaseOwner(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyInstanceDatabaseOwnerWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyInstanceDatabaseOwnerRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifySecurityGroup(*map[string]interface{}) (*map[string]interface{}, error)
	ModifySecurityGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifySecurityGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifySecurityGroupRule(*map[string]interface{}) (*map[string]interface{}, error)
	ModifySecurityGroupRuleWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifySecurityGroupRuleRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifySecurityGroupRuleName(*map[string]interface{}) (*map[string]interface{}, error)
	ModifySecurityGroupRuleNameWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifySecurityGroupRuleNameRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	OverrideDBInstance(*map[string]interface{}) (*map[string]interface{}, error)
	OverrideDBInstanceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	OverrideDBInstanceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RebootDBInstance(*map[string]interface{}) (*map[string]interface{}, error)
	RebootDBInstanceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RebootDBInstanceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ReleaseDBInstanceEip(*map[string]interface{}) (*map[string]interface{}, error)
	ReleaseDBInstanceEipWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ReleaseDBInstanceEipRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ResetDBParameterGroup(*map[string]interface{}) (*map[string]interface{}, error)
	ResetDBParameterGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ResetDBParameterGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RestoreDBInstanceFromDBBackup(*map[string]interface{}) (*map[string]interface{}, error)
	RestoreDBInstanceFromDBBackupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RestoreDBInstanceFromDBBackupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SecurityGroupRelation(*map[string]interface{}) (*map[string]interface{}, error)
	SecurityGroupRelationWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SecurityGroupRelationRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	StatisticDBInstances(*map[string]interface{}) (*map[string]interface{}, error)
	StatisticDBInstancesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	StatisticDBInstancesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SwitchDBInstanceHA(*map[string]interface{}) (*map[string]interface{}, error)
	SwitchDBInstanceHAWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SwitchDBInstanceHARequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateDBInstanceOrder(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateDBInstanceOrderWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateDBInstanceOrderRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateDBInstanceVersion(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateDBInstanceVersionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateDBInstanceVersionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateResourceProtection(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateResourceProtectionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateResourceProtectionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})
}

var _ PostgresqlAPI = (*postgresql.Postgresql)(nil)
