// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package monitoriface provides an interface to enable mocking the monitor service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package monitoriface

import (
	"github.com/KscSDK/ksc-sdk-go/service/monitor"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

// MonitorAPI provides an interface to enable mocking the
// monitor.Monitor service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // monitor.
//    func myFunc(svc monitoriface.MonitorAPI) bool {
//        // Make svc.GetMetricStatistics request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := monitor.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockMonitorClient struct {
//        monitoriface.MonitorAPI
//    }
//    func (m *mockMonitorClient) GetMetricStatistics(input *map[string]interface{}) (*map[string]interface{}, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockMonitorClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type MonitorAPI interface {
	GetMetricStatistics(*map[string]interface{}) (*map[string]interface{}, error)
	GetMetricStatisticsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetMetricStatisticsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListMetrics(*map[string]interface{}) (*map[string]interface{}, error)
	ListMetricsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListMetricsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})
}

var _ MonitorAPI = (*monitor.Monitor)(nil)
