// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package kisiface provides an interface to enable mocking the kis service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package kisiface

import (
	"github.com/KscSDK/ksc-sdk-go/service/kis"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

// KisAPI provides an interface to enable mocking the
// kis.Kis service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // kis.
//    func myFunc(svc kisiface.KisAPI) bool {
//        // Make svc.QueryServerBatchIds request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := kis.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockKisClient struct {
//        kisiface.KisAPI
//    }
//    func (m *mockKisClient) QueryServerBatchIds(input *map[string]interface{}) (*map[string]interface{}, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockKisClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type KisAPI interface {
	QueryServerBatchIds(*map[string]interface{}) (*map[string]interface{}, error)
	QueryServerBatchIdsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	QueryServerBatchIdsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	QueryServerOrderInfos(*map[string]interface{}) (*map[string]interface{}, error)
	QueryServerOrderInfosWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	QueryServerOrderInfosRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	QuerySwitchBatchIds(*map[string]interface{}) (*map[string]interface{}, error)
	QuerySwitchBatchIdsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	QuerySwitchBatchIdsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	QuerySwitchOrderInfos(*map[string]interface{}) (*map[string]interface{}, error)
	QuerySwitchOrderInfosWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	QuerySwitchOrderInfosRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})
}

var _ KisAPI = (*kis.Kis)(nil)
