// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package kcev2iface provides an interface to enable mocking the kcev2 service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package kcev2iface

import (
	"github.com/KscSDK/ksc-sdk-go/service/kcev2"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

// Kcev2API provides an interface to enable mocking the
// kcev2.Kcev2 service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // kcev2.
//    func myFunc(svc kcev2iface.Kcev2API) bool {
//        // Make svc.CreateCluster request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := kcev2.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockKcev2Client struct {
//        kcev2iface.Kcev2API
//    }
//    func (m *mockKcev2Client) CreateCluster(input *map[string]interface{}) (*map[string]interface{}, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockKcev2Client{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type Kcev2API interface {
	CreateCluster(*map[string]interface{}) (*map[string]interface{}, error)
	CreateClusterWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateClusterRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})
}

var _ Kcev2API = (*kcev2.Kcev2)(nil)
