// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package kcmiface provides an interface to enable mocking the kcm service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package kcmiface

import (
	"github.com/KscSDK/ksc-sdk-go/service/kcm"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

// KcmAPI provides an interface to enable mocking the
// kcm.Kcm service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // kcm.
//    func myFunc(svc kcmiface.KcmAPI) bool {
//        // Make svc.CreateCertificate request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := kcm.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockKcmClient struct {
//        kcmiface.KcmAPI
//    }
//    func (m *mockKcmClient) CreateCertificate(input *map[string]interface{}) (*map[string]interface{}, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockKcmClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type KcmAPI interface {
	CreateCertificate(*map[string]interface{}) (*map[string]interface{}, error)
	CreateCertificateWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateCertificateRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteCertificate(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteCertificateWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteCertificateRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeCertificates(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeCertificatesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeCertificatesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyCertificate(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyCertificateWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyCertificateRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})
}

var _ KcmAPI = (*kcm.Kcm)(nil)
