// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package iamiface provides an interface to enable mocking the iam service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package iamiface

import (
	"github.com/KscSDK/ksc-sdk-go/service/iam"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
)

// IamAPI provides an interface to enable mocking the
// iam.Iam service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // iam.
//    func myFunc(svc iamiface.IamAPI) bool {
//        // Make svc.AccountListRoles request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := iam.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockIamClient struct {
//        iamiface.IamAPI
//    }
//    func (m *mockIamClient) AccountListRoles(input *map[string]interface{}) (*map[string]interface{}, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockIamClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type IamAPI interface {
	AccountListRoles(*map[string]interface{}) (*map[string]interface{}, error)
	AccountListRolesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AccountListRolesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AddProjectMember(*map[string]interface{}) (*map[string]interface{}, error)
	AddProjectMemberWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AddProjectMemberRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AddUserToGroup(*map[string]interface{}) (*map[string]interface{}, error)
	AddUserToGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AddUserToGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachGroupPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	AttachGroupPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachGroupPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachRolePolicy(*map[string]interface{}) (*map[string]interface{}, error)
	AttachRolePolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachRolePolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachUserPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	AttachUserPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachUserPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	BatchGetInstanceProjectInfo(*map[string]interface{}) (*map[string]interface{}, error)
	BatchGetInstanceProjectInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	BatchGetInstanceProjectInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	BatchGetProjectInfo(*map[string]interface{}) (*map[string]interface{}, error)
	BatchGetProjectInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	BatchGetProjectInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ChangePassword(*map[string]interface{}) (*map[string]interface{}, error)
	ChangePasswordWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ChangePasswordRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CheckUserEnableMFA(*map[string]interface{}) (*map[string]interface{}, error)
	CheckUserEnableMFAWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CheckUserEnableMFARequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CheckUserSessionCode(*map[string]interface{}) (*map[string]interface{}, error)
	CheckUserSessionCodeWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CheckUserSessionCodeRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateAccessKey(*map[string]interface{}) (*map[string]interface{}, error)
	CreateAccessKeyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateAccessKeyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateAccount(*map[string]interface{}) (*map[string]interface{}, error)
	CreateAccountWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateAccountRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateGroup(*map[string]interface{}) (*map[string]interface{}, error)
	CreateGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateLoginProfile(*map[string]interface{}) (*map[string]interface{}, error)
	CreateLoginProfileWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateLoginProfileRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreatePolicy(*map[string]interface{}) (*map[string]interface{}, error)
	CreatePolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreatePolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreatePolicyVersion(*map[string]interface{}) (*map[string]interface{}, error)
	CreatePolicyVersionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreatePolicyVersionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateProject(*map[string]interface{}) (*map[string]interface{}, error)
	CreateProjectWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateProjectRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateRole(*map[string]interface{}) (*map[string]interface{}, error)
	CreateRoleWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateRoleRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateUser(*map[string]interface{}) (*map[string]interface{}, error)
	CreateUserWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateUserRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateVirtualMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	CreateVirtualMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateVirtualMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeactivateAccountMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	DeactivateAccountMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeactivateAccountMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeactivateMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	DeactivateMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeactivateMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteAccessKey(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteAccessKeyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteAccessKeyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteGroup(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteIdentityAndProjectRelation(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteIdentityAndProjectRelationWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteIdentityAndProjectRelationRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteLoginProfile(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteLoginProfileWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteLoginProfileRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeletePolicy(*map[string]interface{}) (*map[string]interface{}, error)
	DeletePolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeletePolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeletePolicyVersion(*map[string]interface{}) (*map[string]interface{}, error)
	DeletePolicyVersionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeletePolicyVersionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteProjectMember(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteProjectMemberWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteProjectMemberRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteRole(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteRoleWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteRoleRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteUser(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteUserWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteUserRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteVirtualMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteVirtualMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteVirtualMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachGroupPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	DetachGroupPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachGroupPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachRolePolicy(*map[string]interface{}) (*map[string]interface{}, error)
	DetachRolePolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachRolePolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachUserPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	DetachUserPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachUserPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableAccountMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	EnableAccountMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableAccountMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	EnableMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableMfaProfile(*map[string]interface{}) (*map[string]interface{}, error)
	EnableMfaProfileWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableMfaProfileRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetAccountAllProjectList(*map[string]interface{}) (*map[string]interface{}, error)
	GetAccountAllProjectListWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetAccountAllProjectListRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetAccountProjectInfo(*map[string]interface{}) (*map[string]interface{}, error)
	GetAccountProjectInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetAccountProjectInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetAccountProjectList(*map[string]interface{}) (*map[string]interface{}, error)
	GetAccountProjectListWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetAccountProjectListRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetAccountProjectTotal(*map[string]interface{}) (*map[string]interface{}, error)
	GetAccountProjectTotalWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetAccountProjectTotalRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetAccountSummary(*map[string]interface{}) (*map[string]interface{}, error)
	GetAccountSummaryWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetAccountSummaryRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetGroup(*map[string]interface{}) (*map[string]interface{}, error)
	GetGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetLoginProfile(*map[string]interface{}) (*map[string]interface{}, error)
	GetLoginProfileWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetLoginProfileRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetMfaProfile(*map[string]interface{}) (*map[string]interface{}, error)
	GetMfaProfileWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetMfaProfileRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetMiniProgramVirtualMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	GetMiniProgramVirtualMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetMiniProgramVirtualMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	GetPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetPolicyVersion(*map[string]interface{}) (*map[string]interface{}, error)
	GetPolicyVersionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetPolicyVersionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetProjectInstanceList(*map[string]interface{}) (*map[string]interface{}, error)
	GetProjectInstanceListWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetProjectInstanceListRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetPwdPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	GetPwdPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetPwdPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetRole(*map[string]interface{}) (*map[string]interface{}, error)
	GetRoleWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetRoleRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetUser(*map[string]interface{}) (*map[string]interface{}, error)
	GetUserWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetUserRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetUserLoginInfo(*map[string]interface{}) (*map[string]interface{}, error)
	GetUserLoginInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetUserLoginInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetUserSession(*map[string]interface{}) (*map[string]interface{}, error)
	GetUserSessionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetUserSessionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetVirtualMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	GetVirtualMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetVirtualMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListAccessKeys(*map[string]interface{}) (*map[string]interface{}, error)
	ListAccessKeysWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListAccessKeysRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListApiLogTpl(*map[string]interface{}) (*map[string]interface{}, error)
	ListApiLogTplWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListApiLogTplRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListAttachedRolePolicies(*map[string]interface{}) (*map[string]interface{}, error)
	ListAttachedRolePoliciesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListAttachedRolePoliciesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListAttachedUserPolicies(*map[string]interface{}) (*map[string]interface{}, error)
	ListAttachedUserPoliciesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListAttachedUserPoliciesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListEntitiesForPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	ListEntitiesForPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListEntitiesForPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListEntityForPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	ListEntityForPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListEntityForPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListGroupPolicies(*map[string]interface{}) (*map[string]interface{}, error)
	ListGroupPoliciesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListGroupPoliciesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListGroups(*map[string]interface{}) (*map[string]interface{}, error)
	ListGroupsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListGroupsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListGroupsForUser(*map[string]interface{}) (*map[string]interface{}, error)
	ListGroupsForUserWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListGroupsForUserRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListMiniProgramVirtualMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	ListMiniProgramVirtualMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListMiniProgramVirtualMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListPolicies(*map[string]interface{}) (*map[string]interface{}, error)
	ListPoliciesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListPoliciesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListPolicyVersions(*map[string]interface{}) (*map[string]interface{}, error)
	ListPolicyVersionsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListPolicyVersionsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListProjectMember(*map[string]interface{}) (*map[string]interface{}, error)
	ListProjectMemberWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListProjectMemberRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListResourceKrn(*map[string]interface{}) (*map[string]interface{}, error)
	ListResourceKrnWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListResourceKrnRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListRoles(*map[string]interface{}) (*map[string]interface{}, error)
	ListRolesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListRolesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListServicePerm(*map[string]interface{}) (*map[string]interface{}, error)
	ListServicePermWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListServicePermRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListServiceRolesTpl(*map[string]interface{}) (*map[string]interface{}, error)
	ListServiceRolesTplWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListServiceRolesTplRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListServicesAndActions(*map[string]interface{}) (*map[string]interface{}, error)
	ListServicesAndActionsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListServicesAndActionsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListUsers(*map[string]interface{}) (*map[string]interface{}, error)
	ListUsersWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListUsersRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListUsersByIds(*map[string]interface{}) (*map[string]interface{}, error)
	ListUsersByIdsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListUsersByIdsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListVirtualMFADevices(*map[string]interface{}) (*map[string]interface{}, error)
	ListVirtualMFADevicesWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListVirtualMFADevicesRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RemoveUserFromGroup(*map[string]interface{}) (*map[string]interface{}, error)
	RemoveUserFromGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RemoveUserFromGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SetDefaultPolicyVersion(*map[string]interface{}) (*map[string]interface{}, error)
	SetDefaultPolicyVersionWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SetDefaultPolicyVersionRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SetMemberViewAllProject(*map[string]interface{}) (*map[string]interface{}, error)
	SetMemberViewAllProjectWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SetMemberViewAllProjectRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SyncMiniProgramVirtualMFADevice(*map[string]interface{}) (*map[string]interface{}, error)
	SyncMiniProgramVirtualMFADeviceWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SyncMiniProgramVirtualMFADeviceRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	Test(*map[string]interface{}) (*map[string]interface{}, error)
	TestWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	TestRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateAccessKey(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateAccessKeyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateAccessKeyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateGroup(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateGroupWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateGroupRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateInstanceProjectId(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateInstanceProjectIdWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateInstanceProjectIdRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateLoginProfile(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateLoginProfileWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateLoginProfileRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdatePolicy(*map[string]interface{}) (*map[string]interface{}, error)
	UpdatePolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdatePolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateProjectInfo(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateProjectInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateProjectInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateProjectStatus(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateProjectStatusWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateProjectStatusRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdatePwdPolicy(*map[string]interface{}) (*map[string]interface{}, error)
	UpdatePwdPolicyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdatePwdPolicyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateRole(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateRoleWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateRoleRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateRoleTrustAccounts(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateRoleTrustAccountsWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateRoleTrustAccountsRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateUser(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateUserWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateUserRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateUserContactInfo(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateUserContactInfoWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateUserContactInfoRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UserLogin(*map[string]interface{}) (*map[string]interface{}, error)
	UserLoginWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UserLoginRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ValidPolicyDocument(*map[string]interface{}) (*map[string]interface{}, error)
	ValidPolicyDocumentWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ValidPolicyDocumentRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ValidProjectId(*map[string]interface{}) (*map[string]interface{}, error)
	ValidProjectIdWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ValidProjectIdRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	VerificateCompany(*map[string]interface{}) (*map[string]interface{}, error)
	VerificateCompanyWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	VerificateCompanyRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	VerificatePerson(*map[string]interface{}) (*map[string]interface{}, error)
	VerificatePersonWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	VerificatePersonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	VerifyMFACode(*map[string]interface{}) (*map[string]interface{}, error)
	VerifyMFACodeWithContext(aws.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	VerifyMFACodeRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})
}

var _ IamAPI = (*iam.Iam)(nil)
